---
- hosts: all

  tasks:
    - name: Ensure svcawxtest group exists
      group:
        name: svcawxtest
        state: present

    - name: Ensure svcawxtest user exists
      user:
        name: svcawxtest
        groups: svcawxtest
        state: present

    - name: authorized_key
      authorized_key:
        user: svcawxtest
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"

    - name: sudo
      copy: 
        src: files/svcawxtest
        dest: /etc/sudoers.d/
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -csf %s
